kind: pipeline
name: singlescargo1604HW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1604-1.0.9
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 0
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlescargo1604SW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1604-1.0.9
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 0
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlescargo1804HW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1804-1.0.9
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 0
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlescargo1804SW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1804-1.0.9
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 0
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlesxargo1604HW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1604-1.0.9
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlesxargo1604SW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1604-1.0.9
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlesxargo1804HW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1804-1.0.9
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: singlesxargo1804SW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1804-1.0.9
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/single_samples.sh

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx
