kind: pipeline
name: hello-rustc1604nightlyHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1604stableHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust-stable:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1604nightlySW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1604stableSW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust-stable:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1804nightlyHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1804stableHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust-stable:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1804nightlySW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustc1804stableSW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust-stable:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1604nightlyHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1604stableHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust-stable:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1604nightlySW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1604stableSW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust-stable:1604-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1804nightlyHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1804stableHW

steps:
- name: HW-test
  image: baiduxlab/sgx-rust-stable:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: HW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1804nightlySW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---


kind: pipeline
name: hello-rustx1804stableSW

steps:
- name: SW-test
  image: baiduxlab/sgx-rust-stable:1804-1.0.7
  privileged: true
  environment:
    SGX_MODE: SW
    XARGO_SGX: 1
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - bash ci/one_sample.sh hello-rust

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

